getwilds/wilds-wdl-library

- .github/workflows/linting.yml
- Adding initial version of the WOMtool/miniWDL/Sprocket linting GitHub Action
- Splits the three tools into separate jobs for better parallelization and more distinct error messages.
- Fixes #2 
- Successfully lints/validates using all three tools as seen below in the successful checks.
> Adding initial version of linting GHA

- .github/workflows/linting.yml
- .github/workflows/testrun.yml
- modules/ww-sra/inputs.json
- modules/ww-sra/options.json
- modules/ww-sra/ww-sra.wdl
- modules/ww-star/inputs.json
- modules/ww-star/options.json
- modules/ww-star/ww-star.wdl
- Adding an initial version of a "test run" GitHub Action that executes a demonstrative run using small but relevant input data to prove the each script's functionality over time, even if outside infrastructure shifts.
- Parallelizes by execution engine and module WDL script, helping to provide a speedy test set.
- Eventually want to "pythonize" this a bit more, this is quite a lot of bash which might be hard to debug in the future.
- Fixes #3 
- GItHub Actions below demonstrate that the test runs work as expected and should scale as modules are added.
> Adding initial version of test run GHA

- vignettes/README.md
- vignettes/ww-sra-star/README.md
- vignettes/ww-sra-star/inputs.json
- vignettes/ww-sra-star/options.json
- vignettes/ww-sra-star/ww-sra-star.wdl
- Adding an initial version of ww-sra-star as our first vignette.
- Need to add test-run logic to run vignettes in addition to modules.
- Fixes #6 
- Ran the workflow locally using all three execution engines, works as expected.
> Adding initial draft of ww-sra-star vignette

- modules/ww-star/ww-star.wdl
- While developing the ww-leukemia workflow, the Sprocket linting tool threw a fit about one of the STAR tasks.
- See GitHub Actions below.
> Fixing Sprocket linting error for ww-star

- modules/ww-sra/ww-sra.wdl
- While developing the ww-leukemia workflow, the Sprocket linting tool threw a fit about one of the STAR tasks.
- See GitHub Actions below.
> Fixing linting issue in ww-sra

- modules/ww-bwa/README.md
- modules/ww-bwa/inputs.json
- modules/ww-bwa/options.json
- modules/ww-bwa/ww-bwa.wdl
This PR adds a module for using BWA (`bwa index` and `bwa mem`)
Adds a folder that contains:
- WDL with two tasks and an example workflow that runs both
- REAMDE in the style of the `ww-star` module README
- `inputs.json` that makes use of the example files that are downloaded via GHA
- `options.json` copied from the `ww-star` module
#18 
See README for example usage
> Add bwa module

- .github/workflows/modules-testrun.yml
- modules/ww-bcftools/README.md
- modules/ww-bcftools/inputs.json
- modules/ww-bcftools/options.json
- modules/ww-bcftools/ww-bcftools.wdl
- For the ww-leukemia workflow, we'll need bcftools mpileup functionality.
- Adding an initial draft of the ww-bcftools module, will add to ww-leukemia next.
- Fixes #29 
- See GitHub Actions below.
- Also ran with a larger dataset via PROOF, works as expected.
> Adding initial version of bcftools module

- modules/ww-ichorcna/ww-ichorcna.wdl
I updated the `ww-bedtools` WDL as part of PR #45 , so I was referencing that branch's version of bedtools in the `ww-ichorcna` WDL. Now that the branch is merged in we need to update the path to use `main`.
> Use main branch path in ichorCNA WDL

- .github/scripts/discover_modules.py
- .github/workflows/modules-testrun.yml
- .gitignore
- modules/ww-testdata/README.md
- modules/ww-testdata/inputs.json
- modules/ww-testdata/options.json
- modules/ww-testdata/ww-testdata.wdl
- Any time a single module gets modified, we execute test runs for _every_ WILDS WDL module, which is a waste.
- Moving the module identification step into its own python script for better maintainability.
- Adding logic to only execute test runs for modules that have been modified in the PR in question.
- Also allows for manual workflow dispatches for specific modules or all modules.
- Fixes #39 
- As seen in the GitHub Actions below, only the `ww-testdata` test run is executed as it's the only one that has been added/modified in this pull request.
- Tested a [workflow dispatch](https://github.com/getwilds/wilds-wdl-library/actions/runs/16041945204) for a specific module (`ww-annotsv`), worked as expected.
- Tested a [workflow dispatch](https://github.com/getwilds/wilds-wdl-library/action …
> Limit Test Runs to Modified WDL's

- modules/ww-samtools/ww-samtools.wdl
Add one line that runs `samtools sort -n` on the merged CRAM before running `samtools fastq`
Closes #56 
Tested on PROOF
> Sort reads after merging

- modules/ww-ichorcna/README.md
- modules/ww-ichorcna/inputs.json
- modules/ww-ichorcna/ww-ichorcna.wdl
- modules/ww-testdata/ww-testdata.wdl
- Switching the `ww-ichorcna` module to use [HMMcopy's `readCounter` for wig file generation](https://github.com/broadinstitute/ichorCNA/wiki/Usage) (as opposed to bedtool's `makewindows`)
- Should work for a larger range of samples across the entire genome.
- Fixes #59 
- Ran locally, works as expected.
- Ran via PROOF with full WGS data, works as expected.
- See GitHub Actions below for chr1 test run.
> Adding HMMcopy readCounter to IchorCNA module

- .github/workflows/vignettes-testrun.yml
- modules/ww-bwa/README.md
- modules/ww-bwa/inputs.json
- modules/ww-bwa/ww-bwa.wdl
- modules/ww-samtools/README.md
Adds functionality allowing our BWA MEM task to take interleaved fastqs (using the `bwa mem -p` flag). 
- Changes the R1 and R2 variable names to "reads" and "mates" to match BWA MEM terminology
- Adds a "paired_end" boolean parameter so that if one FASTQ is passed we know if it should be considered interleaved or single-end
Closes #55 
- Tested on PROOF and locally and works well
> Bwa interleaved

- modules/ww-gatk/README.md
- modules/ww-gatk/ww-gatk.wdl
- Upon testing the ww-leukemia workflow with full WGS data, the rate-limiting steps were clearly identified as Mutect2 and HaplotypeCaller (~10hrs), GATK can be pretty slow with variant calling.
- To speed these steps up, we can parallelize variant calling across numerous genomic intervals, i.e. split the genome into 50 pieces and have 50 different CPU's take one piece.
- Adding interval splitting and result merging tasks and demonstrating parallelization in the unit test workflow.
- Fixes #73 
- Submitted via PROOF, significant speed-up
- See GitHub Actions below
> Enabling GATK Parallelization

- modules/ww-bwa/ww-bwa.wdl
- modules/ww-samtools/ww-samtools.wdl
- While testing ww-leukemia with full WGS data, Manta was throwing a fit about having read name overlaps and not enough paired reads. Seemed super strange, so we checked alignment stats with `samtools flagstats` and mate information wasn't being properly passed during the conversion from CRAM to interleaved fastq.
- Upon switching to paired fastq's, the issue was resolved. As such, the `crams_to_fastq` task in `ww-samtools` should be updated accordingly to produce separate R1/R2 paired fastq's rather than a single interleaved one.
- Also adding a quick cleanup steps to the end of `ww-bwa` tasks, temporary files are pretty huge.
- Fixes #74 
- Submitted on PROOF within the ww-leukemia workflow, aligns properly, and completes analysis as expected.
- See GitHub Action test runs below.
> Converting CRAM's to Paired Fastq's rather than Interleaved

- modules/ww-gatk/README.md
- modules/ww-gatk/ww-gatk.wdl
- Limiting GATK SplitIntervals to canonical chromosomes by default for better reliability.
- Also adding back in the internally parallelized versions of HaplotypeCaller and Mutect2
- Scatter-gather approach works fine, but still duplicates a ton of data.
- Updating a few variable/file names for consistency while we're at it.
- Fixes #82
- Fixes #80 (again)
- Ran on PROOF, works as expected.
- See GitHub Action test runs below.
> Fixing GATK SplitIntervals and Adding Internal Parallelization Back In

- modules/ww-star/ww-star.wdl
- vignettes/ww-sra-star/README.md
- vignettes/ww-sra-star/ww-sra-star.wdl
- Recently realized that the previous vignette test run actually failed with ww-sra-star.
- Seemed like a one-off error having to do with Docker pull limit.
- Just retriggering the GH Action by fixing the metadata URL.
- Also added a cleanup step in STAR index task to reduce data duplication.
- Still need to update the vignettes test run GHA to mirror the modules test run, but that'll be a different PR.
- Fixes #75 
- See GitHub Action test runs below.
> Fixing ww-sra-star test run and ww-star ref duplication

- modules/ww-annovar/README.md
- modules/ww-annovar/ww-annovar.wdl
- Adding inputs to the `annovar_annotate` task to specify the number of CPU's and memory allocation for the task.
- 2 CPU's and 8GB should be plenty for 99% of jobs, but already ran into an edge case with super deep WGS samples.
- Fixes #96
- Very minor change, no actual function change, just upping resources.
- See GitHub Actions below.
> Adding CPU's and memory allocation to Annovar task inputs

- workflows/ww-leukemia/ww-leukemia.wdl
- Unfortunately ran into memory issues with real WGS samples (~80GB crams, 5M variants)
- Memory request was minimal previously, just need to up it a bit and should be good to go.
- Related to #96 
- Minor change, shouldn't effect functionality.
- Going to test with full cohort of leukemia WGS samples.
> Upping the runtime resources for Annovar in ww-leukemia

- Makefile
- Currently the `make lint_miniwdl` command upon failure shows the error message but give a non-error response code (`0`). 
- An error should return an error response code (e.g., `2`) 
- This fixes that by showing the output of the error message and giving a proper error code (test it by introduce an error in a file (e.g., `ww-annotsv/ww-annotsv.wdl`), run `make lint_miniwdl MODULE=ww-annotsv`, then run `echo $?` which gives you the last exit status, which should be `2`)
#110 
- introduce an error in a file (e.g., `ww-annotsv/ww-annotsv.wdl`)
- run `make lint_miniwdl MODULE=ww-annotsv`
- then run `echo $?` which gives you the last exit status, which should be `2`
> make non-verbose miniwdl check actually throw an error code upon failure

- .github/workflows/modules-testrun.yml
- Makefile
fix #133 
- This uses `wdlparse` - a little rust package I created. The current flow with this tool is to install via cargo from the repo itself via releases (e.g., `cargo install --git https://github.com/getwilds/wdlparse --tag v0.0.5`). In that repo I have a github action that builds and puts binaries on the associated releases page for each git tag. If we decide to go this way could publish to crates.io and a bit easier to install. 
- This requires the `jq` tool as well, but I'd imagine most folks that write code would have it
- Installing `wdlparse` requires `cargo` (and therefore rust) - but I think we can figure out precompiled binaries that don't require either - let me know. 
Let me know if you'd prefer to stick with the current setup of sed/awk. The payoff right now may seem not …
> use wdlparse rust cli tool to get workflow name insetad of sed/awk
